# Generated by Django 4.2.6 on 2023-11-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamescenerio",
            name="characters",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="gamescenerio",
            name="locations",
            field=models.ImageField(default=None, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="gamescenerio",
            name="maps",
            field=models.ImageField(default=None, null=True, upload_to=""),
        ),
    ]
