# Generated by Django 4.2.6 on 2023-11-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg_app", "0002_gamescenerio_characters_gamescenerio_locations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamescenerio",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamescenerio",
            name="characters",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamescenerio",
            name="locations",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="gamescenerio",
            name="maps",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
