# Generated by Django 4.2.6 on 2023-12-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg_app", "0003_alter_gamescenerio_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamescenerio",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
