# Generated by Django 4.2.6 on 2023-12-23 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rpg_app", "0005_chapter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamescenerio",
            name="body",
        ),
        migrations.RemoveField(
            model_name="gamescenerio",
            name="characters",
        ),
        migrations.RemoveField(
            model_name="gamescenerio",
            name="locations",
        ),
        migrations.RemoveField(
            model_name="gamescenerio",
            name="maps",
        ),
    ]
