# Generated by Django 4.2.6 on 2024-01-30 17:57

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rpg_app", "0007_alter_chapter_game_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="body",
            field=django_quill.fields.QuillField(),
        ),
    ]
