# Generated by Django 4.2.6 on 2024-01-31 18:06

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("rpg_app", "0008_alter_chapter_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("race", models.CharField(max_length=100)),
                ("info", django_quill.fields.QuillField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
