# Generated by Django 4.2.6 on 2024-02-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rpg_app", "0009_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="game_scenario",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="rpg_app.gamescenerio"),
        ),
    ]
